"""
Keyword Argument Engine
"""

__date__ = "2026-06-12"
__author__ = "NedeeshaWeerasuriya"
__version__ = "0.1"

import inspect
import itertools
from typing import Callable, Iterator, Any
from dataclasses import dataclass
from ArcMemory import (
    ArcState,
    ObjectState,
)
from ArcHeuristics import HeuristicSummary
from ArcRelations import RelationalGraph, collect_relation_scores, add_relational_kwargs
from helpers import ALL_DIRECTIONS, COLOUR_SET

# -----------------------------------------------------------------------------
# Data Classes
# -----------------------------------------------------------------------------


@dataclass(frozen=True)
class SetSpecificKwarg:
    def resolve(self, original_state: "ArcState") -> Any:
        raise NotImplementedError()


@dataclass(frozen=True)
class OriginalGridKwarg(SetSpecificKwarg):
    def resolve(self, original_state: "ArcState") -> Any:
        return original_state.grid_state


@dataclass(frozen=True)
class BackgroundColourKwarg(SetSpecificKwarg):
    def resolve(self, original_state: "ArcState") -> Any:
        return original_state.grid_state.background_colour


ORIGINAL_GRID_KWARG = OriginalGridKwarg()
BACKGROUND_COLOUR_KWARG = BackgroundColourKwarg()


@dataclass(frozen=True)
class PropertyKwarg:
    """
    Represents a kwarg which is conditioned on a specific property of an object.
    """

    object_property: str
    mapping: tuple[tuple[Any, Any], ...]
    support_score: float = 0.0
    default_value: Any = None

    def resolve_for_object(self, obj: "ObjectState", graph=None) -> Any:
        """
        Given an object, find the corresponding kwarg value based on the mapping.
        """
        if hasattr(obj, self.object_property):
            value = getattr(obj, self.object_property)
            for prop_value, kwarg_value in self.mapping:
                if prop_value == value:
                    return kwarg_value
        return self.default_value


# -----------------------------------------------------------------------------
# Keyword Argument Engine
# -----------------------------------------------------------------------------


def build_kwarg_pool(
    state_cache: dict[int, dict[str, ArcState]], hs: HeuristicSummary
) -> dict[str, list]:
    """
    Get all possible parameter values from the Heuristic Summary which will be used by the DSL primitives.
    """
    pool: dict[str, set] = {}

    # General parameters
    pool.setdefault("quarter_turn", set()).update({1, 2, 3})
    pool.setdefault("direction_str", set()).update(
        {"horizontal", "vertical", "diagonal", "anti-diagonal"}
    )
    # Set default parameters that will be updated
    pool.setdefault("original_grid", set()).add(ORIGINAL_GRID_KWARG)
    pool.setdefault("background_colour", set()).add(BACKGROUND_COLOUR_KWARG)

    # Grid related parameters
    for gd in hs.grid_differences:
        in_state = state_cache[gd.set_id]["input"]
        out_state = state_cache[gd.set_id]["output"]
        # Colour related parameters
        if gd.colour_changed:
            pool.setdefault("in_colour", set()).update([c for c in gd.input_colours])
            pool.setdefault("out_colour", set()).update([c for c in gd.output_colours])
            pool.setdefault("new_colours", set()).update([c for c in gd.new_colours])
            pool.setdefault("removed_colours", set()).update(
                [c for c in gd.removed_colours]
            )
            if gd.new_colours:
                pool.setdefault("new_colour_set", set()).add(tuple(gd.new_colours))
            if gd.removed_colours:
                pool.setdefault("removed_colour_set", set()).add(
                    tuple(gd.removed_colours)
                )

        pool.setdefault("in_shape", set()).add(in_state.grid_state.dimensions)
        pool.setdefault("out_shape", set()).add(out_state.grid_state.dimensions)

    # Object related parameters
    for obj_list in hs.object_transformations:
        for od in obj_list:
            in_state: ArcState = state_cache[od.set_id]["input"]
            in_obj: ObjectState = in_state.objects[od.input_object_id]
            out_state: ArcState = state_cache[od.set_id]["output"]
            out_obj: ObjectState = out_state.objects[od.output_object_id]

            # Shape related parameters
            pool.setdefault("obj_in_shape", set()).add(in_obj.area)
            pool.setdefault("obj_out_shape", set()).add(out_obj.area)

            pool.setdefault("in_centroid", set()).add(in_obj.centroid)
            pool.setdefault("out_centroid", set()).add(out_obj.centroid)
            pool.setdefault("in_bbox", set()).add(in_obj.bounding_box)
            pool.setdefault("out_bbox", set()).add(out_obj.bounding_box)

            # Colour related parameters
            pool.setdefault("obj_in_colour", set()).add(in_obj.colour)
            pool.setdefault("obj_out_colour", set()).add(out_obj.colour)
            pool.setdefault("obj_colours", set()).add((in_obj.colour, out_obj.colour))

            # Mutation related parameters
            # pool.setdefault("mutation_types", set()).update(od.mutation_types)
            pool.setdefault("direction_vector", set()).add(od.direction_vector)
            pool.setdefault("scale", set()).add(od.scale)
            pool.setdefault("filled", set()).add(od.filled)


    # Relational parameters
    relational_scores = collect_relation_scores(state_cache, hs.object_transformations)
    add_relational_kwargs(pool, relational_scores)

    # Check if direction_vector is associated with other object properties
    # (for example all objects with a certain colour are moving in the same direction)
    # print(f"Property Associations: {hs.property_associations}")
    for prop_assoc in hs.property_associations:
        mapping_dict = {k: next(iter(v)) for k, v in prop_assoc.mapping.items()}
        property_kwarg = PropertyKwarg(
            object_property=prop_assoc.object_property,
            mapping=tuple(mapping_dict.items()),
            support_score=prop_assoc.support_score,
        )
        pool.setdefault(prop_assoc.kwarg, set()).add(property_kwarg)

    # Split related parameters
    if hs.split_grid:
        split_map = {direction for direction, active in hs.split_grid.items() if active}
        # For now keep only a single string value
        if split_map:
            pool.setdefault("split_axis", set()).update(split_map)
    return pool


def required_kwargs(func: Callable) -> set[str]:
    """
    Get the required keyword arguments for a given function that must be provided to run.
    """
    sig = inspect.signature(func, follow_wrapped=True)
    params = list(sig.parameters.values())
    required_params = set()
    for param in params[1:]:
        if param.kind in (param.VAR_POSITIONAL, param.VAR_KEYWORD):
            continue
        if param.default is inspect.Parameter.empty:
            required_params.add(param.name)
    return required_params


def prune_primitives_required_kwargs(
    primitives: list[Callable], kwarg_pool: dict[str, list]
) -> list[Callable]:
    """
    Prune the list of primitives based on the required keyword arguments and the available kwarg pool.
    """
    pruned_primitives = []
    for primitive in primitives:
        required_params = required_kwargs(primitive)
        if all(param in kwarg_pool for param in required_params):
            pruned_primitives.append(primitive)
    return pruned_primitives


def iter_relevant_kwargs(
    func: Callable, kwarg_pool: dict[str, list]
) -> Iterator[dict[str, any]]:
    """
    Check which parameters are relevant for a given function.
    Iterate a list of possible parameter combinations from the pool.
    """
    # check if all required kwargs are present in the kwarg pool
    check_requirement = all(kwarg_pool.get(name) for name in required_kwargs(func))
    if not check_requirement:
        return

    wrapper_params = inspect.signature(func, follow_wrapped=False).parameters
    inner_params = inspect.signature(func, follow_wrapped=True).parameters
    all_params = {**wrapper_params, **inner_params}

    relevant_kwargs = [k for k in all_params if k in kwarg_pool]

    if not relevant_kwargs:
        yield {}
        return

    kwarg_values = [kwarg_pool[k] for k in relevant_kwargs]
    for combination in itertools.product(*kwarg_values):
        kwarg_comb = dict(zip(relevant_kwargs, combination))
        for kwarg, val in kwarg_comb.items():
            if kwarg.endswith("_set") and isinstance(val, tuple):
                kwarg_comb[kwarg] = set(val)
        yield kwarg_comb


def check_relevant_kwargs(func: callable, kwarg_pool: dict[str, list]) -> list[dict]:
    """
    Check which parameters are relevant for a given function and return a list of possible parameter combinations from the pool.
    """
    wrapper_params = inspect.signature(func, follow_wrapped=False)
    inner_params = inspect.signature(func, follow_wrapped=True)

    relevant_kwargs = {
        k: kwarg_pool[k] for k in inner_params.parameters if k in kwarg_pool
    }
    relevant_kwargs.update(
        {k: kwarg_pool[k] for k in wrapper_params.parameters if k in kwarg_pool}
    )
    # sig = inspect.signature(func)
    # relevant_kwargs = {k: kwarg_pool[k] for k in sig.parameters if k in kwarg_pool}

    return relevant_kwargs


{
    "train": [
        {
            "input": [
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 2, 0, 0, 0, 5, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 2, 2, 2, 0, 8, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 2, 0, 8, 0, 0, 8, 2, 0, 0, 0, 0, 3, 3, 3, 3, 0, 0, 0],
                [0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 3, 0, 8, 0, 0, 3, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0],
                [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 3, 3, 3, 3, 3, 3, 0],
                [0, 0, 0, 0, 1, 1, 1, 0, 0, 8, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 1, 0, 0, 5, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 1, 0, 5, 0, 5, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            ],
            "output": [
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 2, 8, 8, 8, 8, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 2, 2, 2, 8, 8, 8, 8, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 2, 8, 8, 8, 8, 8, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 2, 8, 8, 8, 8, 8, 2, 0, 0, 0, 0, 3, 3, 3, 3, 0, 0, 0],
                [0, 0, 0, 2, 8, 8, 8, 8, 8, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0],
                [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 3, 3, 3, 3, 3, 3, 0],
                [0, 0, 0, 0, 1, 1, 1, 5, 5, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 1, 5, 5, 5, 5, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 1, 5, 5, 5, 5, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 1, 5, 5, 5, 5, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 1, 5, 5, 5, 5, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            ],
        },
        {
            "input": [
                [0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 2, 0, 0, 0, 0, 0, 3, 0, 2, 0, 0, 6, 6, 6, 0, 0],
                [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 6, 0, 3, 0, 0],
                [0, 0, 2, 2, 2, 0, 3, 0, 0, 0, 2, 0, 0, 6, 0, 0, 0, 0],
                [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 6, 6, 6, 6, 6],
                [0, 0, 0, 0, 2, 0, 0, 0, 8, 0, 2, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 3],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 0, 0, 4, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 4, 0, 8, 0],
                [3, 0, 0, 0, 0, 0, 0, 4, 8, 0, 3, 0, 8, 0, 4, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 8, 0, 4, 0, 0, 0],
                [0, 0, 0, 3, 0, 0, 0, 4, 4, 4, 4, 4, 0, 0, 4, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            ],
            "output": [
                [0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 2, 2, 2, 2, 2, 3, 3, 3, 2, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 2, 3, 3, 3, 3, 3, 3, 3, 2, 0, 0, 6, 6, 6, 0, 0],
                [0, 0, 2, 3, 3, 3, 3, 3, 3, 3, 2, 0, 0, 6, 0, 0, 0, 0],
                [0, 0, 2, 2, 2, 3, 3, 3, 3, 3, 2, 0, 0, 6, 0, 0, 0, 0],
                [0, 0, 0, 0, 2, 3, 3, 3, 3, 3, 2, 0, 0, 6, 6, 6, 6, 6],
                [0, 0, 0, 0, 2, 3, 3, 3, 3, 3, 2, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 2, 3, 3, 3, 3, 3, 2, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 8, 8, 4, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 4, 8, 8, 8, 8, 8, 8, 4, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 4, 8, 8, 8, 8, 8, 8, 4, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 4, 8, 8, 8, 8, 8, 8, 4, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 4, 8, 8, 8, 8, 8, 8, 4, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 8, 8, 4, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            ],
        },
        {
            "input": [
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0],
                [0, 0, 0, 3, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0],
                [0, 3, 3, 3, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
                [0, 3, 0, 0, 0, 8, 0, 0, 8, 0, 3, 0, 0, 0],
                [0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
                [0, 3, 3, 3, 0, 0, 0, 0, 0, 0, 3, 3, 0, 0],
                [0, 0, 0, 3, 0, 6, 0, 0, 2, 0, 0, 3, 0, 0],
                [0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0],
                [0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0],
                [0, 0, 3, 0, 0, 0, 0, 6, 0, 0, 0, 3, 0, 0],
                [0, 0, 3, 0, 0, 6, 0, 3, 3, 3, 3, 3, 0, 0],
                [0, 0, 3, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
                [0, 0, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            ],
            "output": [
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0],
                [0, 0, 0, 3, 6, 6, 6, 6, 6, 6, 3, 0, 0, 0],
                [0, 3, 3, 3, 6, 6, 6, 6, 6, 6, 3, 0, 0, 0],
                [0, 3, 6, 6, 6, 6, 6, 6, 6, 6, 3, 0, 0, 0],
                [0, 3, 6, 6, 6, 6, 6, 6, 6, 6, 3, 0, 0, 0],
                [0, 3, 3, 3, 6, 6, 6, 6, 6, 6, 3, 3, 0, 0],
                [0, 0, 0, 3, 6, 6, 6, 6, 6, 6, 6, 3, 0, 0],
                [0, 0, 0, 3, 6, 6, 6, 6, 6, 6, 6, 3, 0, 0],
                [0, 0, 3, 3, 6, 6, 6, 6, 6, 6, 6, 3, 0, 0],
                [0, 0, 3, 6, 6, 6, 6, 6, 6, 6, 6, 3, 0, 0],
                [0, 0, 3, 6, 6, 6, 6, 3, 3, 3, 3, 3, 0, 0],
                [0, 0, 3, 6, 6, 6, 6, 3, 0, 0, 0, 0, 0, 0],
                [0, 0, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            ],
        },
    ],
    "test": [
        {
            "input": [
                [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    2,
                    2,
                    2,
                    2,
                    2,
                    2,
                    2,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    0,
                    1,
                ],
                [
                    0,
                    0,
                    0,
                    2,
                    0,
                    0,
                    0,
                    0,
                    0,
                    2,
                    2,
                    2,
                    0,
                    0,
                    0,
                    0,
                    3,
                    0,
                    0,
                    0,
                    0,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    2,
                    0,
                    6,
                    0,
                    0,
                    8,
                    0,
                    0,
                    2,
                    0,
                    0,
                    0,
                    0,
                    3,
                    0,
                    0,
                    6,
                    0,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    2,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    2,
                    0,
                    0,
                    3,
                    3,
                    3,
                    0,
                    0,
                    0,
                    0,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    2,
                    2,
                    2,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    2,
                    0,
                    0,
                    3,
                    0,
                    0,
                    0,
                    0,
                    8,
                    0,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    2,
                    0,
                    0,
                    1,
                    0,
                    6,
                    0,
                    0,
                    0,
                    0,
                    2,
                    0,
                    0,
                    3,
                    8,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    2,
                    0,
                    0,
                    0,
                    0,
                    0,
                    2,
                    2,
                    2,
                    2,
                    2,
                    0,
                    0,
                    3,
                    0,
                    0,
                    0,
                    8,
                    0,
                    0,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    2,
                    0,
                    0,
                    0,
                    0,
                    0,
                    2,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    2,
                    2,
                    2,
                    2,
                    2,
                    2,
                    2,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    3,
                    3,
                    3,
                    3,
                    0,
                    0,
                    0,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    0,
                    8,
                    0,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    3,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    0,
                    0,
                    0,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    8,
                    8,
                    8,
                    8,
                    8,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    3,
                    3,
                    3,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    8,
                    0,
                    0,
                    0,
                    8,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    8,
                    8,
                    8,
                    8,
                    8,
                    8,
                    0,
                    8,
                    0,
                    8,
                    0,
                    0,
                    0,
                    0,
                    3,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    8,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    8,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                ],
                [
                    0,
                    0,
                    8,
                    0,
                    4,
                    0,
                    0,
                    0,
                    0,
                    3,
                    0,
                    8,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    8,
                    0,
                    0,
                    0,
                    4,
                    0,
                    0,
                    0,
                    0,
                    8,
                    0,
                    0,
                    0,
                    7,
                    7,
                    7,
                    7,
                    7,
                    7,
                    7,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    8,
                    0,
                    3,
                    0,
                    0,
                    0,
                    0,
                    4,
                    0,
                    8,
                    0,
                    0,
                    0,
                    7,
                    0,
                    0,
                    0,
                    0,
                    0,
                    7,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    8,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    8,
                    0,
                    0,
                    0,
                    7,
                    0,
                    2,
                    0,
                    1,
                    0,
                    7,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    8,
                    0,
                    0,
                    8,
                    8,
                    8,
                    8,
                    0,
                    0,
                    8,
                    0,
                    0,
                    0,
                    7,
                    0,
                    0,
                    0,
                    0,
                    0,
                    7,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    8,
                    8,
                    8,
                    8,
                    0,
                    0,
                    8,
                    8,
                    8,
                    8,
                    0,
                    0,
                    0,
                    7,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    7,
                    7,
                    7,
                    7,
                    7,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    0,
                    0,
                    0,
                ],
            ],
            "output": [
                [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    2,
                    2,
                    2,
                    2,
                    2,
                    2,
                    2,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    2,
                    1,
                    1,
                    1,
                    1,
                    1,
                    2,
                    2,
                    2,
                    0,
                    0,
                    0,
                    0,
                    3,
                    8,
                    8,
                    8,
                    8,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    2,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    2,
                    0,
                    0,
                    0,
                    0,
                    3,
                    8,
                    8,
                    8,
                    8,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    2,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    2,
                    0,
                    0,
                    3,
                    3,
                    3,
                    8,
                    8,
                    8,
                    8,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    2,
                    2,
                    2,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    2,
                    0,
                    0,
                    3,
                    8,
                    8,
                    8,
                    8,
                    8,
                    8,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    2,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    2,
                    0,
                    0,
                    3,
                    8,
                    8,
                    8,
                    8,
                    8,
                    8,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    2,
                    1,
                    1,
                    1,
                    1,
                    1,
                    2,
                    2,
                    2,
                    2,
                    2,
                    0,
                    0,
                    3,
                    8,
                    8,
                    8,
                    8,
                    8,
                    8,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    2,
                    1,
                    1,
                    1,
                    1,
                    1,
                    2,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    8,
                    8,
                    8,
                    8,
                    8,
                    8,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    2,
                    2,
                    2,
                    2,
                    2,
                    2,
                    2,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    8,
                    8,
                    8,
                    8,
                    8,
                    8,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    3,
                    3,
                    3,
                    8,
                    8,
                    8,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    8,
                    8,
                    8,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    8,
                    8,
                    8,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    8,
                    8,
                    8,
                    8,
                    8,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    3,
                    3,
                    3,
                    3,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    8,
                    4,
                    4,
                    4,
                    8,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    8,
                    8,
                    8,
                    8,
                    8,
                    8,
                    4,
                    4,
                    4,
                    8,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    8,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    8,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    8,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    8,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    8,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    8,
                    0,
                    0,
                    0,
                    7,
                    7,
                    7,
                    7,
                    7,
                    7,
                    7,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    8,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    8,
                    0,
                    0,
                    0,
                    7,
                    0,
                    0,
                    0,
                    0,
                    0,
                    7,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    8,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    4,
                    8,
                    0,
                    0,
                    0,
                    7,
                    0,
                    0,
                    0,
                    0,
                    0,
                    7,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    8,
                    4,
                    4,
                    8,
                    8,
                    8,
                    8,
                    4,
                    4,
                    8,
                    0,
                    0,
                    0,
                    7,
                    0,
                    0,
                    0,
                    0,
                    0,
                    7,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    8,
                    8,
                    8,
                    8,
                    0,
                    0,
                    8,
                    8,
                    8,
                    8,
                    0,
                    0,
                    0,
                    7,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    7,
                    7,
                    7,
                    7,
                    7,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
            ],
        }
    ],
}
